djangoProject2/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from app01.views import depart,user,mobile,admin,account

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('depart/list/',depart.depart_list),
    path('depart/add/',depart.depart_add),
    path('depart/delete/',depart.depart_delete),
    path('depart/<int:nid>/edit/',depart.depart_edit),
    path('user/list/',user.user_list),
    path('user/add2/',user.user_add2),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/',user.user_delete),
    path('mobile/list/',mobile.mobile_list),
    path('mobile/add/',mobile.mobile_add),
    path('mobile/<int:nid>/edit/', mobile.mobile_edit),
    path('mobile/<int:nid>/delete/', mobile.mobile_delete),
    path('admin/list/', admin.admin),
    path('admin/add/', admin.add),
    path("admin/<int:nid>/edit/",admin.edit),
    path("admin/<int:nid>/reset/",admin.reset),
    path("login/",account.login),
    path("logout/",account.Logout),
    path("image/code/", account.image_code)
]

views/account.py
from django.shortcuts import render,redirect,HttpResponse
from django import  forms
from app01.utils.encrypt import md5
from app01 import models
from app01.utils.code import check_code
from io import BytesIO
class LoginForm(forms.Form):
    user_name=forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required=True
    )
    password=forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={"class":"form-control"}),
        required = True

    )
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput,
        required=True

    )
    def clean_password(self):
        pwd=self.cleaned_data.get("password")
        return md5(pwd)

def login(request):
    if request.method=="GET":
        form = LoginForm()
        return render(request,'login.html',{'form':form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        user_input=form.cleaned_data.pop('code')
        code=request.session.get('image_code','')
        if code.upper() != user_input.upper():
            form.add_error("code", "验证码错误")
            return render(request,'login.html',{'form':form})
        admin_object= models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password","用户名或密码错误")
            return render(request,'login.html',{'form':form})
        request.session["info"]={'id':admin_object.id,'name':admin_object.user_name}
        request.session.set_expiry(60*60*24*7)
        return redirect('/admin/list/')
    return render(request,'login.html',{'form':form})
def Logout(request):
    request.session.clear()
    return redirect("/login/")
def image_code(request):
    img,string=check_code()
    request.session['image_code']=string
    request.session.set_expiry(60)
    stream=BytesIO()
    img.save(stream,'png')
    return HttpResponse(stream.getvalue())

templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 10px" class="clearfix">
                <a class="btn btn-success" href="/admin/add/">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    新建管理员
                </a>
                <div style="float: right;width: 300px">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search for..."
                                   value="{{ search_data }}">
                            <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                        </span>
                        </div><!-- /input-group -->
                    </form>

                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in datalist %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.user_name }}</td>
                        <td>*********</td>
                        <td><a href="/admin/{{ obj.id }}/reset/">重置密码</a></td>
                        <td>
                            <a class="btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn-danger btn-xs" href="/mobile/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

    </div>




{% endblock %}

templates/change.html
{% extends 'layout.html' %}

{% block content %}
 <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ field.label }}</label>
                        {{ field }}
                         <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                    {% endfor  %}
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/depart_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建部门</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">标题</label>
                        <input type="text" class="form-control" name="title" placeholder="标题">
                    </div>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/depart_edit.html
{% extends 'layout.html' %}
{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建部门</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">标题</label>
                        <input type="text" class="form-control" name="title" placeholder="标题" value="{{ object.title }}">
                    </div>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/depart_list.html
{% extends 'layout.html' %}
{% block content %}
<div>
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/depart/add/" >
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建部门
            </a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                部门列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in datalist %}
                <tr>
                    <th >{{ obj.id }}</th>
                    <td>{{ obj.title }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit/">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/depart/delete/?id={{ obj.id }}">删除</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>
{% endblock %}

templates/error.html
{% extends "layout.html" %} }}
{% block content %}
<div class="container">
<div class="alert alert-danger" role="alert">
      <strong>{{ msg }}</strong> 请重试
</div>
</div>

{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">联通用户管理系统</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">部门管理</a></li>
                <li><a href="/user/list/">用户管理</a></li>
                <li><a href="/mobile/list/">靓号管理</a></li>
                <li><a href="/admin/list/">管理员</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.session.info.name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li><a href="#">我的信息</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div>
        {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
 {% block js %}{% endblock %}
</body>
</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <style>
        .account{
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            padding: 20px 40px;
        }
        .account h2{
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form novalidate method="post">
        {% csrf_token %}
        <div class="form-group">
            <label >用户名</label>
            {{ form.user_name }}
            <span style="color: red">{{ form.user_name.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label >密码</label>
           {{ form.password }}
             <span style="color: red">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
        <div class="col-xs-7">
            {{ form.code }}
            <span style="color: red">{{ form.code.errors.0 }}</span>
        </div>
        <div class="col-xs-5">
            <img id="img-code" src="/image/code/" style="width: 125px">
        </div>
            </div>
            </div>
        <input type="submit" value="登录" class="btn btn-primary">
    </form>
</div>


</body>
</html>

templates/mobile_add.html
{% extends 'layout.html' %}

{% block content %}
 <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建靓号</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ field.label }}</label>
                        {{ field }}
                         <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                    {% endfor  %}
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/user_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建员工</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">姓名</label>
                        <input type="text" class="form-control" name="name" placeholder="姓名">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">密码</label>
                        <input type="text" class="form-control" name="pwd" placeholder="密码">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">年龄</label>
                        <input type="text" class="form-control" name="age" placeholder="年龄">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">入职时间</label>
                        <input type="text" class="form-control" name="ct" placeholder="入职时间">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">余额</label>
                        <input type="text" class="form-control" name="ac" placeholder="余额">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail">性别</label>
                        <select class="form-control" name="gd">
                            {% for item in gender_choices %}
                            <option value="{{ item.0 }}">{{ item.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/user_add2.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block content %}
 <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建员工</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ field.label }}</label>
                        {{ field }}
                         <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                    {% endfor  %}
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}
{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
    $(function () {
        $('#id_create_time').datepicker({
            format:"yyyy-mm-dd",
            startDate:"0",
            language:"zh-CN",
            autoclose:true,
            autocomplete:false
        })
    })
    </script>

{% endblock %}

templates/user_edit.html
{% extends 'layout.html' %}
{% block content %}
   <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">编辑员工</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ field.label }}</label>
                        {{ field }}
                         <span style="color: red"> {{ field.errors.0 }}</span>
                    </div>
                    {% endfor  %}
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
<div>
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user/add2/" >
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建用户
            </a>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in datalist %}
                <tr>
                    <th>{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.password }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.account }}</td>
                    <td>{{ obj.create_time |date:"Y-m-d " }}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>
                        <a class="btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                        <a class="btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                    </td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

    </div>

</div>



{% endblock %}

templates/user_mobile.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 10px" class="clearfix">
                <a class="btn btn-success" href="/mobile/add/">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    新建靓号
                </a>
                <div style="float: right;width: 300px">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search for..."
                                   value="{{ search_data }}">
                            <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                        </span>
                        </div><!-- /input-group -->
                    </form>

                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>等级</th>
                    <th>状态</th>
                    <th>价格</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in datalist %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.price }}</td>
                        <td>
                            <a class="btn-primary btn-xs" href="/mobile/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn-danger btn-xs" href="/mobile/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </div>

    </div>




{% endblock %}